/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

import { exampleRule } from "../rules/example-rule";

export const recommended = {
  rules: {
    'example-rule': exampleRule
  }
}
